# This is a basic workflow to help you get started with Actions

name: Super-linter

on:
  
  push:
    branches: [ "main" ]
    
jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
         DEFAULT_BRANCH: main
      
      
